### ISSUE TITLE
Double press 'S' to set focus

### ISSUE THREAD

**Issue by VladSavitsky** [MikesGlitch/Focus-First-Input#1]
First of all - thanks for great extension!
Extension works but I need to hold 'Alt' and double press 'S' to have focus in input field.

**Comment by MikesGlitch** [comment]
Thanks,  unfortunately we're limited to to functionality provided by chrome. 

url: chrome://extensions/shortcuts

Right now it doesn't account for double tapping, but you can rebind to whatever you want.
