### ISSUE TITLE
Just the opposite of what I expected

### ISSUE THREAD

**Issue by PacoH** [MikesGlitch/Focus-First-Input#3]
"Adds a shortcut that focuses the cursor on the first text input."

I thought this meant more like "first text field." I tried it on a page that forced me to use the trackpad to select the window so I could scroll, something that I despise to have to do. Instead it went right to the Search bar. I though maybe it was because the bar had the 'phantom' word 'Search' in it, but watching your video, I see that this is the purpose of the extension. In fact, it seems to have broken this site entirely. I turned it off and then deleted it but now I cannot even gain access with the trackpad and none of the links work at all, either selecting them with the trackpad or with the spacebar or Enter. I can't even scroll with the trackpad. I deleted cookies, cleared the cache and rebooted Chrome, and still no response. It was working before.

[What Made the Titan Submersible Design Unconventional? | NOVA | PBS](https://www.pbs.org/wgbh/nova/video/oceangate-titan-submersible/)

**Comment by MikesGlitch** [comment]
Yeah the purpose of the extension isn't to move the mouse, it's to focus the text cursor on the text input. It's mostly for people who don't want to use a mouse/touchpad at all. I don't think it would be a good idea to hijack the users mouse cursor - that just seems a bit too invasive.

Regarding the website not working, that has nothing to do with this extension. Clearing cookies/rebooting/etc wouldn't impact the functionality of the site. This extension is a very small piece of Javascript that simply adds a keyboard shortcut. 

I had a look at the website a minute ago and it seems to work fine. 

Closing this.
![test](https://github.com/MikesGlitch/Focus-First-Input/assets/5285928/cb5ae78f-bb9e-49f4-a886-2c40afdb3b87)
